Repository OleksandrBrusyltsev/Visiting_Grandpa-s_Village, pull requests merged in 2024-08, with the labels that each got.

#101 Updated forms: added CAPTCHA, feedback forms, reduced sizes, improved error handling, and adjusted styles
  public/images/visit/combo.png
  public/sprite.svg
  src/actions/recaptchaValidation.ts
  src/actions/tgBotAction.ts
  src/app/[locale]/(client)/booking/page.tsx
  src/app/[locale]/icon.png
  src/components/BookingComponent/BookingComponent.tsx
  src/components/BookingComponent/stub/Contact.module.scss
  src/components/BookingComponent/stub/ContactForm.tsx
  src/components/BookingComponent/stub/Error.tsx
  src/components/BookingComponent/stub/Feedback.module.scss
  src/components/BookingComponent/stub/Main.module.scss
  src/components/BookingComponent/stub/Main.tsx
  src/components/BookingComponent/stub/Success.tsx
  src/components/ContactsComponent/ContactsList/ContactsList.tsx
  src/components/Footer/Footer.module.scss
  src/components/Footer/Footer.tsx
  src/components/GalleryItemPage/GalleryItemPage.tsx
  src/components/GalleryItemPage/SwiperGalleryItem.scss
  src/components/Visit/Visit.module.scss
  src/components/Visit/Visit.tsx
  src/components/ui/Button/Button.tsx
  src/components/ui/Modal/Modal.module.scss
  src/components/ui/Modal/Modal.tsx
  src/data/admin/tgUserId.js
  src/data/bookingStub/index.js
Labels: enhancement

#113 Feat/create rules
  public/images/contacts/google-map.jpg
  public/images/grandpas/Grandpa6.png
  public/images/grandpas/Grandpa7.png
  src/app/[locale]/(client)/booking/rules/page.tsx
  src/components/Rules/Rules.module.scss
  src/components/Rules/Rules.tsx
  src/data/rules/index.js
Labels: enhancement

#125 fixed according the issue №120 (ex. of 10, 11)
  localization/uk.json
  public/sprite.svg
  src/actions/getData.ts
  src/app/[locale]/(client)/[...rest]/page.tsx
  src/app/[locale]/(client)/gallery/[chapter]/page.tsx
  src/app/[locale]/(client)/houses/[house]/[room]/page.tsx
  src/app/[locale]/(client)/houses/[house]/page.tsx
  src/app/[locale]/(client)/template.tsx
  src/app/[locale]/icon.png
  src/app/favicon.ico
  src/components/AskGrandpa/AskGrandpa.tsx
  src/components/Breadcrumbs/Breadcrumbs.tsx
  src/components/ContactsComponent/ContactsComponent.tsx
  src/components/Gallery/Gallery.module.scss
  src/components/GalleryItemPage/GalleryItemPage.module.scss
  src/components/GalleryItemPage/GalleryItemPage.tsx
  src/components/House/HeroSection/HeroSection.tsx
  src/components/House/House.tsx
  src/components/Houses/HouseItem.tsx
  src/components/Houses/Houses.tsx
  src/components/Houses/HousesList.tsx
  src/components/Rules/Rules.module.scss
  src/components/Visit/Visit.module.scss
Labels: bug, enhancement

#156 Update the text for the contact section
  src/components/ContactsComponent/ContactsList/ContactsList.tsx
  src/components/ContactsComponent/RouteInfo/RouteInfo.tsx
Labels: bug

#157 Feat/seo text
  src/app/[locale]/(client)/booking/options/page.tsx
  src/app/[locale]/(client)/booking/page.tsx
  src/app/[locale]/(client)/booking/payment/page.tsx
  src/app/[locale]/(client)/booking/rules/page.tsx
  src/app/[locale]/(client)/contacts/page.tsx
  src/app/[locale]/(client)/entertainment/page.tsx
  src/app/[locale]/(client)/gallery/[chapter]/page.tsx
  src/app/[locale]/(client)/gallery/page.tsx
  src/app/[locale]/(client)/houses/[house]/[room]/page.tsx
  src/app/[locale]/(client)/houses/[house]/page.tsx
  src/app/[locale]/(client)/houses/page.tsx
  src/app/[locale]/(client)/layout.tsx
  src/app/[locale]/(client)/meals/page.tsx
  src/app/[locale]/(client)/page.tsx
  src/app/[locale]/layout.tsx
  src/app/[locale]/not-found.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
  src/components/BookingComponent/components/Calendar/Calendar.tsx
  src/components/BookingComponent/stub/Error.tsx
  src/components/BookingComponent/stub/Success.tsx
  src/components/ContactsComponent/ContactsList/ContactsList.tsx
  src/components/ContactsComponent/FAQ/FAQ.tsx
  src/components/ContactsComponent/FAQ/faqData.json
  src/components/ContactsComponent/GoogleMap/CustomMarker.tsx
  src/components/ContactsComponent/GoogleMap/GoogleMap.tsx
  src/components/ContactsComponent/RouteInfo/RouteInfo.tsx
  src/components/ContactsComponent/TelegramBlock/TelegramBlock.module.scss
  src/components/ContactsComponent/TelegramBlock/TelegramBlock.tsx
  src/components/Entertainment/Entertainment.module.scss
  src/components/Entertainment/Entertainment.tsx
  src/components/Footer/Footer.tsx
  src/components/Gallery/Gallery.tsx
  src/components/Gallery/GalleryItem.tsx
  src/components/GalleryItemPage/GalleryItemPage.tsx
  src/components/Header/Header.tsx
  src/components/Header/Navigation.tsx
  src/components/Header/PopupMenu.tsx
  src/components/Hero/Hero.module.scss
  src/components/Hero/Hero.tsx
  src/components/House/Gallery/Gallery.tsx
  src/components/House/Gallery/MainSwiper/MainSwiper.tsx
  src/components/House/HeroSection/HeroSection.tsx
  src/components/House/House.module.scss
  src/components/House/House.tsx
  src/components/House/Map/Pin/Pin.tsx
  src/components/Houses/HouseItem.tsx
  src/components/Houses/Houses.module.scss
  src/components/Houses/Houses.tsx
  src/components/Meals/Meals.tsx
  src/components/Meals/MealsBlock.module.scss
  src/components/Meals/MealsBlock.tsx
  src/components/NotFound/NotFound.tsx
  src/components/Rules/Rules.tsx
  src/components/Visit/Visit.tsx
  src/data/houses/index.js
  src/data/meals/index.js
  src/functions/MarkdownPreview.js
  src/functions/generateGalleryMetadata.ts
  src/functions/generatePageMetadata.ts
Labels: enhancement, semver:patch
